### ISSUE TITLE
Create Kanban Board For the proejct

### ISSUE THREAD

**Issue by ouasamine** [Strangeal/personal-catalog#38]
The team working on this project consists of 3 members: @ouasamine @Strangeal @ndikumanaisaie 

- @ndikumanaisaie is working on Team member#1 tasks
- @ouasamine  is working on Team member#2 tasks
- @Strangeal  is working on Team member#3 tasks

Link to [Knaban Board](https://github.com/users/Strangeal/projects/2)

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @ouasamine, @ndikumanaisaie and @Strangeal,

Good job so far!
✔️ Kanban boards are complete
✔️ Tasks are well assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Kindly add descriptions for all your tasks. These are examples of tasks without a description.

  1 | 2
  :---:|:---:
  ![shue](https://user-images.githubusercontent.com/36542986/211281611-36d9e7aa-324e-407a-9e63-bd21a4392034.jpg) | ![djdir](https://user-images.githubusercontent.com/36542986/211281614-5dc6ffd2-4810-4bb0-a761-500e68a82476.jpg)

- [x] Team member one, @ndikumanaisaie, does not have an issue for this task. Kindly create it

  ![dhduer](https://user-images.githubusercontent.com/36542986/211281606-e97e284d-fb0b-4a86-ac14-2e08fbe10a42.jpg)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by gemmen29** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 💯 
- Descriptive info ✔️ 

![](https://media.giphy.com/media/mCIjCgs3nWQWfJZvPA/giphy-downsized-large.gif)

## Optional suggestions

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ouasamine** [comment]
thank you @TedLivist & @gemmen29
